### ISSUE TITLE
Can't handle unicode string as URL (Python 3)

### ISSUE THREAD

**Issue by danni** [sveetch/django-feedparser#6]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django_feedparser/views.py", line 47, in get_context_data
    context['feed_rendered'] = self.render_feed(feed_renderer, feed_url)
  File "/usr/local/lib/python3.4/dist-packages/django_feedparser/views.py", line 31, in render_feed
    return renderer().render(url, template=self.feed_template, expiration=self.feed_cache_expiration)
  File "/usr/local/lib/python3.4/dist-packages/django_feedparser/renderer.py", line 138, in render
    return render_to_string(template, self.get_context(url, expiration))
  File "/usr/local/lib/python3.4/dist-packages/django_feedparser/renderer.py", line 126, in get_context
    self._feed = self.get(url, expiration)
  File "/usr/local/lib/python3.4/dist-packages/django_feedparser/renderer.py", line 99, in get
    'id': hashlib.md5(url).hexdigest(),
TypeError: Unicode-objects must be encoded before hashing
```

Workaround is to pass the URL as a bytes string (`b""`)

**Comment by sveetch** [comment]
Sorry for the answer delay, but i do not have a Python3 install actually.

 From what i see, it's almost an issue from the user, i could add something like "string.encode('utf-8')" in my code but i don't think this is a good idea to force this behavior. Better let this as it for now.

**Comment by danni** [comment]
You can test the same functionality in Python2 by passing `from __future__ import unicode_literals`.
